### ISSUE TITLE
Paging is not working on https://vladislavantonyuk.github.io/

### ISSUE THREAD

**Issue by ArpitViradiyaCrowncon** [VladislavAntonyuk/vladislavantonyuk.github.io#100]
Steps to replicate:
1) Go to [https://vladislavantonyuk.github.io/](url)
2) Now we are on first page, now click on next page
3) Now click on next page, now observe we are still on first page but now 1st page is selected, before (step 2) is not selected

**Comment by VladislavAntonyuk** [comment]
The Blazor take some time to load the page and refreshes content after it has loaded. Paging is working after Blazor is loaded.
