### ISSUE TITLE
SpeechToText from CommunityToolkit.Maui.Media

### ISSUE THREAD

**Issue by enigith** [VladislavAntonyuk/vladislavantonyuk.github.io#104]
Hello Vladislav,

i use the SpeechToText-Implementation from CommunityToolkit.Maui.Media.
Under Android, the behaviour is, that the speech-dialog ends automaticly, if it doesn't detect any sound anymore.
That's graet, because the user must only start the speech-dialog, so there is no need for an addition click to stop the speech-dialog.
Is it possible, to implement this behaviour also for iOS and Windows?

Thanks in advance
jagger

**Comment by VladislavAntonyuk** [comment]
We made some adjustments for .NET 9 release. Hope, it will solve your issue.
