### ISSUE TITLE
Error has occurred

### ISSUE THREAD

**Issue by GeorgeLeithead** [VladislavAntonyuk/vladislavantonyuk.github.io#112]
Vlad,

When going to your site home page, and then selecting the "Read Full Article" option for the article entitled "Azure Active Directory authentication in .NET Aspire Distributed Application", I get an "Error has occurred".

![image](https://github.com/user-attachments/assets/0473214f-0139-40a2-9f0c-e9fc3f9b0599)

**Comment by GeorgeLeithead** [comment]
I just tried again, and I no longer get the error.

**Comment by VladislavAntonyuk** [comment]
Try to clean cache.
