### ISSUE TITLE
Keychain access issue

### ISSUE THREAD

**Issue by DavidShochet** [VladislavAntonyuk/vladislavantonyuk.github.io#34]
Hi Vladislav,

I used your sample to implement Azure B2C authentication on our .Net MAUI app. It does work on Android, but on iOS, I get an exception:

> The application does not have keychain access groups enabled in the Entitlements.plist. As a result, there was a failure to save to the iOS keychain. The keychain access group 'MC7LD4Y4UQ.com.microsoft.adalcache' is not enabled in the Entitlements.plist. Also, use the WithIosKeychainSecurityGroup api to set the keychain access group. See https://aka.ms/msal-net-enable-keychain-groups for more details on enabling keychain access groups and entitlements.

But I do have it enabled:

     `<key>keychain-access-groups</key>
	<array>
		<string>$(AppIdentifierPrefix)com.microsoft.adalcache</string>
	</array>`

I am stuck with this for long time. Please advise! 

Thank you, and Слава Україні!

Dmitriy Reznik

**Comment by VladislavAntonyuk** [comment]
Героям Слава!

Hi Dmitriy,

You can explicitly set in csproj that you want to use the Entitlement file `<CodesignEntitlement>Entitlements.plist</CodesignEntitlement>`:

I have such configurations:

```xml
	<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('windows')) == 'false' and $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios' and $(Configuration) == 'Release'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<CodesignEntitlement>Entitlements.plist</CodesignEntitlement>
		<ArchiveOnBuild>true</ArchiveOnBuild>
	</PropertyGroup>

	<PropertyGroup Condition="$([MSBuild]::IsOSPlatform('windows')) == 'false' and $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios' and $(Configuration) == 'Debug'">
		<RuntimeIdentifier>ios-arm64</RuntimeIdentifier>
		<RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
		<CreatePackage>false</CreatePackage>
	</PropertyGroup>
```

**Comment by DavidShochet** [comment]
Hi @VladislavAntonyuk,

Thank you for the quick answer. 

I do have it:

`	<PropertyGroup Condition="'$(TargetFramework)'=='net7.0-ios'">
		<CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
	</PropertyGroup>`

And yet I am having this issue...

**Comment by VladislavAntonyuk** [comment]
This is exactly the issue you have: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/783

Unfortunately, I don't have an apple developer account to test it on a real device.
you can also try to check the status of the keychain before processing authentication:
https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-net-xamarin-ios-considerations#troubleshooting-keychain-access

**Comment by DavidShochet** [comment]
Hi Vladislav,

Thank you for your answer. 

I looked at the code that you suggested:

`var queryRecord = new SecRecord(SecKind.GenericPassword)
{
    Service = "",
    Account = "SomeTeamId",
    Accessible = SecAccessible.Always
};

SecRecord match = SecKeyChain.QueryAsRecord(queryRecord, out SecStatusCode resultCode);

if (resultCode == SecStatusCode.ItemNotFound)
{
    SecKeyChain.Add(queryRecord);
    match = SecKeyChain.QueryAsRecord(queryRecord, out resultCode);
}`

I am not sure I understand how it is supposed to be used. Should I replace some values? 
When I use it as is, resultCode is Success. 

There is something else that I noticed. The exception I am getting is this:

"The application does not have keychain access groups enabled in the Entitlements.plist. As a result, there was a failure to save to the iOS keychain. The keychain access group '**MC7LD4Y4UQ**.com.microsoft.adalcache' is not enabled in the Entitlements.plist. Also, use the WithIosKeychainSecurityGroup api to set the keychain access group. See https://aka.ms/msal-net-enable-keychain-groups for more details on enabling keychain access groups and entitlements."

And I see the prefix mentioned in the error message in the distribution provisioning profile on our Azure build pipeline:

`- task: DotNetCoreCLI@2
  displayName: dotnet publish ($(BuildConfiguration))
  condition: eq(${{ parameters.BuildConfig }}, 'Debug')
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'LATICRETE_MobileApp/LATICRETE_MobileApp.csproj'
    arguments: '-f:net7.0-ios -c:$(BuildConfiguration) -r ios-arm64 /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false'
    zipAfterPublish: false
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: dotnet publish ($(BuildConfiguration))
  condition: eq(${{ parameters.BuildConfig }}, 'Release')
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'LATICRETE_MobileApp/LATICRETE_MobileApp.csproj'
    arguments: '-f:net7.0-ios -c:$(BuildConfiguration) -r ios-arm64 /p:ArchiveOnBuild=true /p:EnableAssemblyILStripping=false /p:CodesignKey="iPhone Distribution: LATICRETE International%2c Inc. (MC7LD4Y4UQ)" /p:CodesignProvision="Laticrete Distribution Profile"'
    zipAfterPublish: false
    modifyOutputPath: false`
    
    It is supposed to be only for Release, and I wonder why it is sought for during our authentication...

**Comment by VladislavAntonyuk** [comment]
the issue happens in the method Save: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/c9bdd0dd191ab2e658a1c949e43e3959fe3d1aa5/src/client/Microsoft.Identity.Client/Platforms/iOS/iOSTokenCacheAccessor.cs#L253
The best option would be to clone the repo and try to debug the code. probably it will provide more information than the general message.

**Comment by DavidShochet** [comment]
Hi Vladislav,

Some Microsoft people suggested me to replace com.microsoft.adalcache in Entitlements.plist and in WithIosKeychainSecurityGroup() with our bundle identifier. And now it works. Weird, isn't it? I still don't know what is wrong with com.microsoft.adalcache.

**Comment by VladislavAntonyuk** [comment]
Thank you for investigating the issue! It’s weird because even at Microsoft docs they suggest to add com.microsoft.adalcache.
