### ISSUE TITLE
How can I replicate the examples ?

### ISSUE THREAD

**Issue by cagriy** [VladislavAntonyuk/vladislavantonyuk.github.io#40]
Hello,

Thanks a lot for great examples. Looking at: https://vladislavantonyuk.github.io/articles/Creating-a-card-stack-layout-using-.NET-MAUI/

Is there a way to replicate examples on this page where the top card smoothly move out or in ? I've downloaded the Pizza example on GitHub but it only makes the top card instantly disappear instead of sliding out.

Many thanks,

Ali

**Comment by VladislavAntonyuk** [comment]
You can add animation to the card like FadeAnimation from CommunityToolkit.MAUI
