### ISSUE TITLE
MAUI MSAL Authentification iOS Keychain Access Error

### ISSUE THREAD

**Issue by JustAnotherLars** [VladislavAntonyuk/vladislavantonyuk.github.io#7]
This guide i used: 
[https://vladislavantonyuk.github.io/articles/Azure-Active-Directory-authentication-in-.NET-MAUI/](url)

When I follow the instructions I get the following error: 

`4Microsoft. Identity.Client.MsalClientException wurde ausgelöst
The application cannot access the iOS keychain for the application publisher (the Teamld is null). This is needed to enable Single Sign On between applications of the same publisher. This is an iOS configuration issue. See https://aka.ms/msal-net-enable-keychain-access`

To me it looks like the error is happening at the following point:

` authenticationClient = PublicClientApplicationBuilder.Create(Constants.ClientId)
`

Do you have any idea how to fix this?

**Comment by VladislavAntonyuk** [comment]
according to the error, you haven't enabled keychain access. See https://aka.ms/msal-net-enable-keychain-access

**Comment by JustAnotherLars** [comment]
Thank you for the prompt reply. Of course, that's what I thought. I am just absolutely not sure where I can activate the Keychain Access. Can you maybe tell me where I can do that?

**Comment by VladislavAntonyuk** [comment]
Create Entitlements.plist file in iOS project if it doesn't exist.
add the next content to it:
```xml

<dict>
  <key>keychain-access-groups</key>
  <array>
    <string>$(AppIdentifierPrefix)com.microsoft.adalcache</string>
  </array>
</dict>
```

**Comment by VladislavAntonyuk** [comment]
@JustAnotherLars Could you please close the issue if it is resolved?
