### ISSUE TITLE
maps + blur panel

### ISSUE THREAD

**Issue by EsferaTech** [VladislavAntonyuk/vladislavantonyuk.github.io#8]
and tried, but I have not been able to make an app with .net maui that contains a map with a custom style and a blur panel at the bottom of the screen to display information, it seems to me a beautiful rest to develop

**Comment by VladislavAntonyuk** [comment]
Could you please provide more information?
Screenshots (actual and desired), sample reproduction source

**Comment by VladislavAntonyuk** [comment]
feel free to reopen it with providing more information
